# ODMAP-aligned reporting ---------------------------------------------------
#
# cast_report_odmap() renders the analysis settings recorded in a
# cast_result (plus user-supplied metadata) into a Markdown report that
# follows the ODMAP (Overview, Data, Model, Assessment, Prediction)
# protocol for reporting species distribution models (Zurell et al. 2020).
# Items the pipeline cannot answer automatically are left as explicit
# "[report]" placeholders so the author can complete them.

#' Render an ODMAP-Aligned Model Report
#'
#' Writes a Markdown report structured after the ODMAP protocol (Overview,
#' Data, Model, Assessment, Prediction; Zurell et al. 2020) from a
#' `cast_result` object. Every section that castSDM can fill from the
#' pipeline is filled automatically; author-specific entries (taxon,
#' purpose, data licence, expertise) are taken from `meta` or left as
#' explicit `[report]` placeholders.
#'
#' @param object A `cast_result` object (from [cast()]).
#' @param path Output file path. Default `"odmap_report.md"`.
#' @param meta Optional named list of report metadata. Recognised keys:
#'   `taxon`, `authors`, `title`, `purpose`, `data_description`,
#'   `data_licence`, `expertise`, `assumptions`.
#' @param verbose Logical. Default `TRUE`.
#'
#' @return The output path (invisibly).
#' @references
#' Zurell, D. et al. (2020). A standard protocol for reporting species
#' distribution models. *Ecography*, 43(9), 1261-1277.
#' @seealso [cast()]
#' @export
cast_report_odmap <- function(object, path = "odmap_report.md",
                              meta = list(), verbose = TRUE) {
  if (!inherits(object, "cast_result")) {
    cli::cli_abort("{.arg object} must be a {.cls cast_result}.")
  }
  meta <- meta %||% list()
  get_meta <- function(key, fallback = "[report]") {
    v <- meta[[key]]
    if (is.null(v) || !length(v) || !nzchar(as.character(v)[1])) fallback
    else as.character(v)[1]
  }

  scr <- object$screen
  fit <- object$fit
  cv <- object$cv
  ev <- object$eval

  diag <- scr$diagnostics %||% list()
  screen_method <- scr$method %||% "unknown"
  fwd_steps <- if (!is.null(diag$path)) nrow(diag$path) else NA_integer_
  fwd_loss <- if (!is.null(diag$final_loss) && is.finite(diag$final_loss)) {
    signif(diag$final_loss, 4)
  } else {
    NA_real_
  }
  fwd_metric <- diag$metric %||% "not recorded"
  n_sel <- length(scr$selected %||% character(0))
  sel_vars <- scr$selected %||% character(0)
  models_used <- names(fit$models)
  cv_info <- if (!is.null(cv)) {
    sprintf("%d-fold spatial (%s) nested CV, selection re-run per fold",
            cv$k, cv$block_method)
  } else {
    "[report] (no spatial CV recorded in this object)"
  }
  eval_src <- if (!is.null(cv)) "nested spatial CV" else "spatial hold-out"
  pred_info <- if (!is.null(object$predict)) {
    sprintf("%d sites predicted", nrow(object$predict$predictions))
  } else {
    "[report] (no spatial prediction recorded in this object)"
  }

  lines <- c(
    sprintf("# ODMAP report: %s", get_meta("title", "Species distribution model")),
    "",
    sprintf("**Taxon**: %s", get_meta("taxon")),
    sprintf("**Authors**: %s", get_meta("authors")),
    sprintf("**Generated by**: castSDM %s (%s)",
            utils::packageVersion("castSDM"), Sys.time()),
    "",
    "## 1. Overview",
    "",
    sprintf("- **Objective / purpose**: %s", get_meta("purpose")),
    sprintf("- **Model category**: correlative SDM (presence-background)"),
    sprintf("- **Algorithms**: %s", paste(models_used, collapse = ", ")),
    "",
    "## 2. Data",
    "",
    sprintf("- **Species data**: %s", get_meta("data_description")),
    sprintf("- **Data licence / accessibility**: %s", get_meta("data_licence")),
    "- **Pseudo-absence design**: background sampling (see `cast_background()`);",
    "  suitability is a relative score, not a calibrated probability",
    "",
    "## 3. Model",
    "",
    sprintf("- **Variable selection**: %s", screen_method),
    sprintf("- **Stage-2 forward search**: %s admission(s), inner-CV %s = %s",
            if (is.na(fwd_steps)) "not recorded" else fwd_steps,
            fwd_metric,
            if (is.na(fwd_loss)) "not recorded" else fwd_loss),
    sprintf("- **Predictors retained**: %s (%d)",
            paste(sel_vars, collapse = ", "), n_sel),
    sprintf("- **Selection leakage control**: %s",
            if (!is.null(cv)) "variable selection is re-run inside every outer spatial CV fold" else
              "not applicable (no CV was run)"),
    sprintf("- **Expertise / prior knowledge used**: %s", get_meta("expertise")),
    "",
    "## 4. Assessment",
    "",
    sprintf("- **Performance estimates (%s)**:", eval_src),
    "```",
    if (!is.null(cv) && nrow(cv$metrics)) {
      paste(utils::capture.output(print(cv$metrics)), collapse = "\n")
    } else if (!is.null(ev) && nrow(ev$metrics)) {
      paste(utils::capture.output(print(ev$metrics)), collapse = "\n")
    } else {
      "[report]"
    },
    "```",
    sprintf("- **Validation design**: %s", cv_info),
    "- **Assumptions and caveats**:",
    sprintf("  %s", get_meta("assumptions",
      "Observational, sampling-biased data; variable selection serves parsimony and does not identify causal mechanisms.")),
    "",
    "## 5. Prediction",
    "",
    sprintf("- **Prediction extent**: %s", pred_info),
    "- **Extrapolation control**: MESS flags on every prediction row",
    "  (`mess`, `extrapolating` columns); optional clamping",
    sprintf("- **Uncertainty layers**: ensemble `hss_sd` (cross-model SD)%s",
            if (!is.null(object$ensemble))
              " (NA where fewer than two models contribute)" else ""),
    ""
  )

  writeLines(lines, path)
  if (verbose) cli::cli_inform("ODMAP report written to {.path {path}}.")
  invisible(path)
}
