# ODMAP-aligned reporting ---------------------------------------------------
#
# cast_report_odmap() renders the analysis settings recorded in a
# cast_result (plus user-supplied metadata) into a Markdown report that
# follows the ODMAP (Overview, Data, Model, Assessment, Prediction)
# protocol for reporting species distribution models (Zurell et al. 2020).
# Items the pipeline cannot answer automatically are left as explicit
# "[report]" placeholders so the author can complete them.

#' Render an ODMAP-Aligned Model Report
#'
#' Writes a Markdown report structured after the ODMAP protocol (Overview,
#' Data, Model, Assessment, Prediction; Zurell et al. 2020) from a
#' `cast_result` object. Every section that castSDM can fill from the
#' pipeline is filled automatically; author-specific entries (taxon,
#' purpose, data licence, expertise) are taken from `meta` or left as
#' explicit `[report]` placeholders.
#'
#' @param object A `cast_result` object (from [cast()]).
#' @param path Output file path. Default `"odmap_report.md"`.
#' @param meta Optional named list of report metadata. Recognised keys:
#'   `taxon`, `authors`, `title`, `purpose`, `data_description`,
#'   `data_licence`, `expertise`, `assumptions`.
#' @param verbose Logical. Default `TRUE`.
#'
#' @return The output path (invisibly).
#' @references
#' Zurell, D. et al. (2020). A standard protocol for reporting species
#' distribution models. *Ecography*, 43(9), 1261-1277.
#' @seealso [cast()]
#' @export
cast_report_odmap <- function(object, path = "odmap_report.md",
                              meta = list(), verbose = TRUE) {
  if (!inherits(object, "cast_result")) {
    cli::cli_abort("{.arg object} must be a {.cls cast_result}.")
  }
  meta <- meta %||% list()
  get_meta <- function(key, fallback = "[report]") {
    v <- meta[[key]]
    if (is.null(v) || !length(v) || !nzchar(as.character(v)[1])) fallback
    else as.character(v)[1]
  }

  scr <- object$screen
  fit <- object$fit
  cv <- object$cv
  ev <- object$eval

  diag <- scr$diagnostics %||% list()
  engine <- diag$engine %||% "unknown"
  alpha <- diag$alpha %||% NA_real_
  n_sel <- length(scr$selected %||% character(0))
  sel_vars <- scr$selected %||% character(0)
  forced_vars <- diag$forced %||% character(0)
  models_used <- names(fit$models)
  cv_info <- if (!is.null(cv)) {
    sprintf("%d-fold spatial (%s) nested CV, selection re-run per fold",
            cv$k, cv$block_method)
  } else {
    "[report] no spatial CV run"
  }
  eval_src <- if (!is.null(cv)) "nested spatial CV" else "spatial hold-out"
  pred_info <- if (!is.null(object$predict)) {
    sprintf("%d sites predicted", nrow(object$predict$predictions))
  } else {
    "[report] no spatial prediction"
  }

  lines <- c(
    sprintf("# ODMAP report: %s", get_meta("title", "Species distribution model")),
    "",
    sprintf("**Taxon**: %s", get_meta("taxon")),
    sprintf("**Authors**: %s", get_meta("authors")),
    sprintf("**Generated by**: castSDM %s (%s)",
            utils::packageVersion("castSDM"), Sys.time()),
    "",
    "## 1. Overview",
    "",
    sprintf("- **Objective / purpose**: %s", get_meta("purpose")),
    sprintf("- **Model category**: correlative SDM (presence-background)"),
    sprintf("- **Algorithms**: %s", paste(models_used, collapse = ", ")),
    "",
    "## 2. Data",
    "",
    sprintf("- **Species data**: %s", get_meta("data_description")),
    sprintf("- **Data licence / accessibility**: %s", get_meta("data_licence")),
    "- **Pseudo-absence design**: background sampling (see `cast_background()`);",
    "  suitability is a relative score, not a calibrated probability",
    "",
    "## 3. Model",
    "",
    sprintf("- **Variable selection engine**: %s", engine),
    sprintf("- **FDR level**: %s", if (is.na(alpha)) "not recorded" else alpha),
    sprintf("- **Predictors retained**: %s (%d)",
            paste(sel_vars, collapse = ", "), n_sel),
    "- **Transfer-critical axes (force_include)**:",
    sprintf("  %s", if (length(forced_vars)) paste(forced_vars, collapse = ", ")
            else "none"),
    "- **Selection leakage control**: variable selection is re-run inside",
    "  every outer spatial CV fold",
    sprintf("- **Expertise / prior knowledge used**: %s", get_meta("expertise")),
    "",
    "## 4. Assessment",
    "",
    sprintf("- **Performance estimates (%s)**:", eval_src),
    "```",
    if (!is.null(cv) && nrow(cv$metrics)) {
      paste(utils::capture.output(print(cv$metrics)), collapse = "\n")
    } else if (!is.null(ev) && nrow(ev$metrics)) {
      paste(utils::capture.output(print(ev$metrics)), collapse = "\n")
    } else {
      "[report]"
    },
    "```",
    sprintf("- **Validation design**: %s", cv_info),
    "- **Assumptions and caveats**:",
    sprintf("  %s", get_meta("assumptions",
      "Observational, sampling-biased data; conditional screening does not prove causal mechanisms.")),
    "",
    "## 5. Prediction",
    "",
    sprintf("- **Prediction extent**: %s", pred_info),
    "- **Extrapolation control**: MESS flags on every prediction row",
    "  (`mess`, `extrapolating` columns); optional clamping",
    sprintf("- **Uncertainty layers**: ensemble `hss_sd` (cross-model SD); %s",
            if (!is.null(object$ensemble))
              "sensitivity `delta_sd` available" else "[report]"),
    ""
  )

  writeLines(lines, path)
  if (verbose) cli::cli_inform("ODMAP report written to {.path {path}}.")
  invisible(path)
}
